host: ""
phoneId: "123123123123123"

vapi:
  orgId: ""
  key: ""

channels:
  - key: ""
    secret: ""
    number: ""

consumers:
  - firstName: ""
    lastName: ""
    zipCode: ""
    birthday: "2000-01-01"
    account: { cardNumber: "1234", sss: "1234", }
    contactInfo: { email: "", phone: "", mobile: "" }
    security: { question: "", answer: "", password: "alpha", passwordRequired: false }